image: gitlab.dsi.universite-paris-saclay.fr:5005/l1infoinitiationsciencedonnees/computerlab/image:latest

build:
  script:
    - pip install -e .

pages:
  script:
    - pip install --upgrade jupyterlab-git
    - pip install "jupyterlite-core >=0.2.0,<0.3.0" "jupyterlite-xeus>=0.1.2,<0.2" litegitpuller
    - pip install git+https://gitlab.dsi.universite-paris-saclay.fr/jupyter/jupylates.git
    - make lite
    - mv _output public
  artifacts:
    paths:
      - public
  only:
    - master
