name: jupylates-jupyterlite

channels:
- https://repo.mamba.pm/emscripten-forge
- https://repo.mamba.pm/conda-forge
- conda-forge

dependencies:
- xeus-python
- ipywidgets

##############################################################################
#- ipywidgets
#- jupytext
#- mystmd

#- pip
#- pip:
#    - "litegitpuller"
#    - "git+https://gitlab.dsi.universite-paris-saclay.fr/jupyter/jupylates.git"


