name: jupylates-jupyterlite

channels:
- https://repo.mamba.pm/emscripten-forge
- https://repo.mamba.pm/conda-forge
- conda-forge

dependencies:
- xeus-python
- ipywidgets

##############################################################################
# Authoring and teaching tools
- jupyterlab-myst>=2.1.0

- matplotlib
- pandas
- seaborn
- ipydatagrid
- tabulate
- pillow
- mscorefonts
- tqdm
- jupytext

- pip
- pip:
    - "litegitpuller"
    - "git+https://gitlab.dsi.universite-paris-saclay.fr/jupyter/jupylates.git"


