name: jupylates-jupyterlite

channels:
- https://repo.mamba.pm/emscripten-forge
- conda-forge

dependencies:
- xeus-python
- ipywidgets
- jupytext
- mystmd

- pip
- pip:
    - "jupyterlab"
    - "jupyter_client"
    - "nbclient"
    - "nbconvert"
    - "litegitpuller"
    - "git+https://gitlab.dsi.universite-paris-saclay.fr/jupyter/jupylates.git"
